# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "5514d874b4d86d58f5a5ed13e80cc16306423b96"

[[deps.TreeSim]]
path = "."
uuid = "dc327cbd-6c9b-4100-9a5f-ed0bbf0cf4d5"
version = "0.1.0"
