name = "TreeSim"
uuid = "dc327cbd-6c9b-4100-9a5f-ed0bbf0cf4d5"
authors = ["michaeltmeehan <michael.meehan1@jcu.edu.au>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
