module TreeSim

include("tree.jl")

export NodeKind,
       Root,
       Binary,
       UnsampledUnary,
       SampledUnary,
       SampledLeaf,
       Node,
       Tree,
       root,
       roots,
       children,
       parent,
       isleaf,
       isinternal,
       isbinary,
       isunary,
       leaves,
       tips,
       internal_nodes,
       nnodes,
       nleaves,
       ninternal,
       preorder,
       postorder,
       breadthfirst,
       ancestors,
       descendants,
       subtree_nodes,
       branch_length,
       node_depths,
       root_to_tip_distances,
       tree_height,
       mean_root_to_tip_distance,
       ncherries,
       validate_tree

end
